### ISSUE TITLE
Redundant cross-compile build?

### ISSUE THREAD

**Issue by izahn** [conda-forge/poppler-feedstock#116]
While preparing a PR to this feedstock I noticed that `build.sh` has this structure:

```
if [ "${CONDA_BUILD_CROSS_COMPILATION}" = "1" ]; then
    unset _CONDA_PYTHON_SYSCONFIGDATA_NAME
    (
        mkdir -p native-build
        pushd native-build
<SNIP>
	cmake ${EXTRA_CMAKE_ARGS} \
	    -DCMAKE_PREFIX_PATH=$BUILD_PREFIX \
	    -DCMAKE_INSTALL_PREFIX=$BUILD_PREFIX \
	    $SRC_DIR
<SNIP>
        ninja -j$CPU_COUNT -v
        ninja install
        popd
    )
    export GI_CROSS_LAUNCHER=$BUILD_PREFIX/libexec/gi-cross-launcher-load.sh
fi

mkdir build && cd build

export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$BUILD_PREFIX/lib/pkgconfig"

cmake ${CMAKE_ARGS} ${EXTRA_CMAKE_ARGS} \
    -GNinja \
    -DCMAKE_PREFIX_PATH=$PREFIX \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    $SRC_DIR

ninja
ninja install
```

Doesn't that run `ninja; ninja install` twice when `CONDA_BUILD_CROSS_COMPILATION == 1`? Is that intentional?

**Comment by pkgw** [comment]
Yes, it is. The reason is the way that the [gobject-introspection][gi] (GI) framework generates its data files. In order to create the data files that allow introspection of a library, the GI tools compile and run a temporary executable that links to the library and queries it at runtime. But if you're cross compiling, you can't run any compiled executables (in general), since those executables are compiled for a different architecture. So we have to do two builds: the first is on the native architecture, just to get the GI tools to generate the data files that they need, then the "real" build with cross-compilation, which has a bit of a hack in place (via the `$GI_CROSS_LAUNCHER` variable) to copy over the magic metadata files rather than trying to generate them.

[gi]: https://gi.readthedocs.io/en/latest/

There are some definite downsides to this approach, but it's the most robust one available given the GI system's need to compile and run an executable. It's a good example of how cross-compilation can make life surprisingly complicated!

Also note that the "native" build installs into $BUILD_PREFIX, so the files that it creates aren't candidates for inclusion in the final package. I forget why the install step is run in the native build, but I'm sure there's a good reason for it.

**Comment by izahn** [comment]
OK thanks for taking time to explain it, I really appreciate it!
